var lang = {
    "yes": "Oui",
    "no": "Non",
    "form.men": "hommes",
    "form.women": "femmes",
    "form.men2": "Un homme",
    "form.women2": "Une femme",
    "form.error.username": "Veuillez saisir votre pseudo",
    "form.error.valid.login": "Veuillez saisir un pseudo valide",
    "form.error.character": "Le pseudo doit contenir au moins 6 caractères",
    "form.error.letters": "Le pseudo ne doit contenir que des lettres et des chiffres",
    "form.error.valid.email": "Veuillez saisir une adresse e-mail valide",
    "form.error.terms": "Veuillez accepter les conditions générales du service",
    "form.error.contact": "Veuillez cocher la case afin d'accepter d'être contacté",
    "form.error.email": "Veuillez saisir votre adresse e-mail",
    "form.error.password": "Veuillez saisir votre mot de passe",
    "form.error.firstname": "Veuillez saisir votre prénom",
    "form.error.lastname": "Veuillez saisir votre nom",
    "form.error.phone": "Veuillez saisir votre numéro de téléphone",
    "form.error.subject": "Veuillez choisir le sujet",
    "form.error.city": "Veuillez saisir votre ville",
    "form.error.message": "Veuillez saisir votre message",
    "form.error.birthdate_day": "Veuillez saisir votre jour de naissance",
    "form.error.birthdate_month": "Veuillez saisir votre mois de naissance",
    "form.error.birthdate_year": "Veuillez saisir votre année de naissance",
    "form.error.age": "Veuillez saisir votre âge",
    "form.gender.man": "Je suis un homme",
    "form.gender.woman": "Je suis une femme",
    "form.search.man": "Je recherche un homme",
    "form.search.woman": "Je recherche une femme",
    "form.gender.man_short": "Un homme",
    "form.gender.woman_short": "Une femme",
    "form.search.man_short": "Un homme",
    "form.search.woman_short": "Une femme",
    "form.gender.man.search": "Je suis un homme qui cherche une femme",
    "form.gender.woman.search": "Je suis une femme qui cherche un homme",
    "form.age": "ans",
    "message.error": "Erreur",
    "message.error.incorrect": "Saisie incorrecte",
    "message.information": "Information",
    "message.alert": "Alerte",
    "message.notice.password": "Vous allez recevoir dans quelques instants votre nouveau mot de passe par e-mail.",
    "message.notice.send": "Votre message a bien été envoyé. Notre service client va vous recontacter très prochainement.",
    "contact.subject.info": "Demande de renseignements",
    "contact.subject.stop": "Je veux suspendre un abonnement",
    "contact.subject.identify": "Je cherche à identifier un prélèvement",
    "contact.subject.challenge": "Je souhaite contester un prélèvement",
    "contact.subject.other": "Divers",
    "message.notice.unsubscribed": "Le désabonnement a bien été pris en compte",
    "message.notice.unsubscribed_failed": "Le désabonnement a échoué. Veuillez contacter le service client",
    "support.form.message.unsubscribe": "Trouver et résilier mon abonnement",
    "support.form.message.inactive": "Nous avons retrouvé votre abonnement, celui-ci n'est plus actif et vous êtes déjà désabonné.",
    "support.form.message.unsubscribed": "Nous avons retrouvé votre abonnement, celui-ci est toujours actif mais vous êtes déjà désabonné.",
    "support.form.message.nothing": "Nous n'avons retrouvé aucun abonnement à partir des informations saisies.",
    "support.form.message.active": "Nous avons retrouvé votre abonnement, celui-ci est actif et vous n'êtes pas encore désabonné.",
    "support.form.message.choice": "Souhaitez-vous procéder à votre désabonnement ?",
    "support.form.message.help": "Pouvons-nous faire autre chose pour vous venir en aide ? Contactez le service client qui se tient à votre disposition !"
};


